# Generated by Django 2.2.4 on 2019-10-16 12:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GroupMembers',
            new_name='GroupMember',
        ),
    ]
